vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "<leader>7", ":Comment c<Enter>")
vim.keymap.set("v", "<leader>8", ":Comment u<Enter>")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<c-u>", "<c-u>zz")
vim.keymap.set("n", "<leader>,", ":Compile d<Enter>")
vim.keymap.set("n", "<leader>.", ":Compile r<Enter>")
vim.keymap.set("n", "<leader>m", ":GenericFormat<Enter>")
vim.keymap.set('t', "<leader>'", [[<C-\><C-n>]],{noremap=true})
vim.keymap.set("n", "<leader>'", ":noh<Enter>")
